"""add steadfast fields to orders

Revision ID: 90f482da2576
Revises: f8b2a41c9e12
Create Date: 2026-09-26 23:46:27.999497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f482da2576'
down_revision = 'f8b2a41c9e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steadfast_consignment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('steadfast_tracking_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('steadfast_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('steadfast_status')
        batch_op.drop_column('steadfast_tracking_code')
        batch_op.drop_column('steadfast_consignment_id')

    # ### end Alembic commands ###
